## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN","NAME"])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = []
app_types_counts = application_df["APPLICATION_TYPE"].value_counts()
app_types_names = app_types_counts.index
n = 0

for app_type_count in app_types_counts:
  if app_type_count<=10:
    app_type = app_types_names[n]
    application_types_to_replace.append(app_type)
  n +=1

print(application_types_to_replace)

['T25', 'T14', 'T29', 'T15', 'T17']

In [ ]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_value_counts = application_df["CLASSIFICATION"].value_counts()
class_value_names = class_value_counts.index
n=0

for classification_count in class_value_counts:
  if classification_count>1:
    print(f'{class_value_names[n]} - {classification_count}')
  n+=1

C1000 - 17326
C2000 - 6074
C1200 - 4837
C3000 - 1918
C2100 - 1883
C7000 - 777
C1700 - 287
C4000 - 194
C5000 - 116
C1270 - 114
C2700 - 104
C2800 - 95
C7100 - 75
C1300 - 58
C1280 - 50
C1230 - 36
C1400 - 34
C7200 - 32
C2300 - 32
C1240 - 30
C8000 - 20
C7120 - 18
C1500 - 16
C1800 - 15
C6000 - 15
C1250 - 14
C8200 - 11
C1238 - 10
C1278 - 10
C1235 - 9
C1237 - 9
C7210 - 7
C2400 - 6
C1720 - 6
C4100 - 6
C1257 - 5
C1600 - 5
C1260 - 3
C2710 - 3
C0 - 3
C3200 - 2
C1234 - 2
C1246 - 2
C1267 - 2
C1256 - 2

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

classifications_to_replace = []
class_types_counts = application_df["CLASSIFICATION"].value_counts()
class_types_names = class_types_counts.index
n = 0

for class_type_count in class_types_counts:
  if class_type_count<=10:
    class_type = class_types_names[n]
    classifications_to_replace.append(class_type)
  n +=1

print(classifications_to_replace)

['C1238', 'C1278', 'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100', 'C1257', 'C1600', 'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246', 'C1267', 'C1256', 'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820', 'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570', 'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561', 'C4500', 'C2150']

In [ ]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
Other      118
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Check replacemnts worked for applications
application_df["APPLICATION_TYPE"].unique()

array(['T10', 'T3', 'T5', 'T7', 'T4', 'T6', 'T2', 'T9', 'T19', 'T8',
       'T13', 'T12', 'Other'], dtype=object)

In [ ]:
# Check replacements worked for categoreies
application_df["CLASSIFICATION"].unique()

array(['C1000', 'C2000', 'C3000', 'C1200', 'C2700', 'C7000', 'C7200',
       'C1700', 'C4000', 'C7100', 'C2800', 'C6000', 'C2100', 'Other',
       'C5000', 'C7120', 'C1800', 'C1400', 'C1270', 'C2300', 'C8200',
       'C1500', 'C1300', 'C1230', 'C1280', 'C1240', 'C1250', 'C8000'],
      dtype=object)

In [ ]:
# Display dataframe
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies_df = pd.get_dummies(application_df)
application_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,APPLICATION_TYPE_T9,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C1230,CLASSIFICATION_C1240,CLASSIFICATION_C1250,CLASSIFICATION_C1270,CLASSIFICATION_C1280,CLASSIFICATION_C1300,CLASSIFICATION_C1400,CLASSIFICATION_C1500,CLASSIFICATION_C1700,CLASSIFICATION_C1800,CLASSIFICATION_C2000,CLASSIFICATION_C2100,CLASSIFICATION_C2300,CLASSIFICATION_C2700,CLASSIFICATION_C2800,CLASSIFICATION_C3000,CLASSIFICATION_C4000,CLASSIFICATION_C5000,CLASSIFICATION_C6000,CLASSIFICATION_C7000,CLASSIFICATION_C7100,CLASSIFICATION_C7120,CLASSIFICATION_C7200,CLASSIFICATION_C8000,CLASSIFICATION_C8200,CLASSIFICATION_Other,USE_CASE_CommunityServ,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
features_array = application_dummies_df.drop(columns=["IS_SUCCESSFUL"]).values

target_array = (application_dummies_df["IS_SUCCESSFUL"]).values

In [ ]:
#Diplay our split target array
target_array

array([1, 1, 0, ..., 0, 1, 0])

In [ ]:
# Display our split features array
features_array

array([[       1,     5000,        0, ...,        0,        1,        0],
       [       1,   108590,        0, ...,        0,        1,        0],
       [       1,     5000,        0, ...,        0,        1,        0],
       ...,
       [       1,     5000,        0, ...,        0,        1,        0],
       [       1,     5000,        0, ...,        0,        1,        0],
       [       1, 36500179,        0, ...,        0,        1,        0]])

In [ ]:
features_df

,STATUS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,APPLICATION_TYPE_T9,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C1230,CLASSIFICATION_C1240,CLASSIFICATION_C1250,CLASSIFICATION_C1270,CLASSIFICATION_C1280,CLASSIFICATION_C1300,CLASSIFICATION_C1400,CLASSIFICATION_C1500,CLASSIFICATION_C1700,CLASSIFICATION_C1800,CLASSIFICATION_C2000,CLASSIFICATION_C2100,CLASSIFICATION_C2300,CLASSIFICATION_C2700,CLASSIFICATION_C2800,CLASSIFICATION_C3000,CLASSIFICATION_C4000,CLASSIFICATION_C5000,CLASSIFICATION_C6000,CLASSIFICATION_C7000,CLASSIFICATION_C7100,CLASSIFICATION_C7120,CLASSIFICATION_C7200,CLASSIFICATION_C8000,CLASSIFICATION_C8200,CLASSIFICATION_Other,USE_CASE_CommunityServ,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
34297,1,5000,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0

In [ ]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(features_df,target_df,random_state=1)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
X_train_scaled

array([[ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       ...,
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687]])

In [ ]:
y_train

array([0, 1, 1, ..., 0, 0, 0])

## Compile, Train and Evaluate the Model

In [ ]:
# Count features
features_count = len(X_train_scaled[0])
features_count

69

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation="relu", input_dim=feature_length))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=25, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 50)                3500

 dense_10 (Dense)            (None, 25)                1275

 dense_11 (Dense)            (None, 1)                 26

=================================================================
Total params: 4801 (18.75 KB)
Trainable params: 4801 (18.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [85]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam",metrics=["accuracy"])

In [86]:
pd.set_option('display.max_columns', None)
display(features_df)

,STATUS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,APPLICATION_TYPE_T9,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C1230,CLASSIFICATION_C1240,CLASSIFICATION_C1250,CLASSIFICATION_C1270,CLASSIFICATION_C1280,CLASSIFICATION_C1300,CLASSIFICATION_C1400,CLASSIFICATION_C1500,CLASSIFICATION_C1700,CLASSIFICATION_C1800,CLASSIFICATION_C2000,CLASSIFICATION_C2100,CLASSIFICATION_C2300,CLASSIFICATION_C2700,CLASSIFICATION_C2800,CLASSIFICATION_C3000,CLASSIFICATION_C4000,CLASSIFICATION_C5000,CLASSIFICATION_C6000,CLASSIFICATION_C7000,CLASSIFICATION_C7100,CLASSIFICATION_C7120,CLASSIFICATION_C7200,CLASSIFICATION_C8000,CLASSIFICATION_C8200,CLASSIFICATION_Other,USE_CASE_CommunityServ,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
34297,1,5000,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0

In [87]:
display(y_train)

array([0, 1, 1, ..., 0, 0, 0])

In [88]:
X_train_scaled

array([[ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       ...,
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.02957055, -0.01870803, ..., -0.07529085,
         0.02925687, -0.02925687]])

In [89]:
# Train the model
fit_nn = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5701 - accuracy: 0.7233
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7300
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7322
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7310
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7336
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7332
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7336
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7344
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7349
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7342
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7357
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7364
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7359
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7353
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7374
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7363
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7367
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7367
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7383
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7375
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7375
Epoch 22/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7382
Epoch 23/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5380 - accuracy: 0.7379
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7378
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7380
Epoch 26/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5376 - accuracy: 0.7378
Epoch 27/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5372 - accuracy: 0.7378
Epoch 28/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5369 - accuracy: 0.7392
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7371
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7372
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7381
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7386
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7387
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7387
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7389
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7388
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7394
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7393
Epoch 40/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5346 - accuracy: 0.7396
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7398
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7393
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7411
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5340 - accuracy: 0.7400
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7409
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7414
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7401
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7411
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7404
Epoch 50/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5334 - accuracy: 0.7407
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5331 - accuracy: 0.7397
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7406
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7414
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7406
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7409
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7406
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5325 - accuracy: 0.7406
Epoch 58/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5321 - accuracy: 0.7405
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7407
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7415
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7412
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7409
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7407
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7404
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7412
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5313 - accuracy: 0.7402
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5313 - accuracy: 0.7407
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7423
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7413
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7406
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7423
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7418
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5312 - accuracy: 0.7414
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5309 - accuracy: 0.7422
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7414
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7412
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7418
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7421
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7416
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7423
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7418
Epoch 82/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5304 - accuracy: 0.7419
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7417
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7427
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7425
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7420
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7414
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7425
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.7426
Epoch 90/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5296 - accuracy: 0.7426
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.7420
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7415
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7430
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7417
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7419
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7424
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7415
Epoch 98/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5290 - accuracy: 0.7414
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7412
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7421

In [91]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5554 - accuracy: 0.7290 - 383ms/epoch - 1ms/step
Loss: 0.5553777813911438, Accuracy: 0.7289795875549316

In [95]:
# Export our model to HDF5 file
nn.save("applicatn_sucess_model1.HDF5")